name: Terraform 

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - terraform/**               
      - terraform-bootstrap/**          
      - .github/workflows/apply.yaml

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest
    env:
      TF_VAR_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_VAR_resource_group_name: ${{ vars.RESOURCE_GROUP_NAME }}
      TF_VAR_prefix: ${{ vars.PREFIX }}
      TF_VAR_location: ${{ vars.LOCATION }}
      TF_VAR_vnet_address_space: ${{ vars.VNET_ADDRESS_SPACE }}
      TF_VAR_app_address_prefixes: ${{ vars.APP_ADDRESS_PREFIXES }}
      TF_VAR_postgresql_address_prefixes: ${{ vars.POSTGRESQL_ADDRESS_PREFIXES }}
      TF_VAR_domain_name: ${{ vars.DOMAIN_NAME }}
      TF_VAR_admin_object_id: ${{ secrets.ADMIN_OBJECT_ID }}
      TF_VAR_admin_username: ${{ secrets.ADMIN_USERNAME }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Validate
        run: terraform validate
        
      - name: Terraform Plan
        run: terraform plan -out=tfplan -input=false
      
      - name: Terraform Apply
        run: terraform apply -input=false tfplan
     
      - name: Summary
        if: success()
        run: echo "Terraform apply complete"
          